// src/content/dialCodes.ts
export type DialCode = { code: string; country: string };

export const dialCodes: DialCode[] = [
  { code: "+94", country: "Sri Lanka" },
  { code: "+61", country: "Australia" },
  { code: "+1", country: "Canada" },
  { code: "+86", country: "China" },
  { code: "+33", country: "France" },
  { code: "+49", country: "Germany" },
  { code: "+852", country: "Hong Kong" },
  { code: "+91", country: "India" },
  { code: "+62", country: "Indonesia" },
  { code: "+39", country: "Italy" },
  { code: "+81", country: "Japan" },
  { code: "+60", country: "Malaysia" },
  { code: "+960", country: "Maldives" },
  { code: "+31", country: "Netherlands" },
  { code: "+64", country: "New Zealand" },
  { code: "+92", country: "Pakistan" },
  { code: "+974", country: "Qatar" },
  { code: "+7", country: "Russia" },
  { code: "+966", country: "Saudi Arabia" },
  { code: "+65", country: "Singapore" },
  { code: "+27", country: "South Africa" },
  { code: "+82", country: "South Korea" },
  { code: "+34", country: "Spain" },
  { code: "+46", country: "Sweden" },
  { code: "+41", country: "Switzerland" },
  { code: "+66", country: "Thailand" },
  { code: "+971", country: "United Arab Emirates" },
  { code: "+44", country: "United Kingdom" },
  { code: "+1", country: "United States" },
];
